### PR TITLE
(maint) adding block passthrough to the libdir core method

### PR DESCRIPTION
**Pull request by Thomas-Franklin**

### CODE REVIEW

**Comment by Thomas-Franklin** [comment]
Issue encountered when doing quick smoke test on master:

```
2019-04-04 15:58:10 - RuntimeError - no block given (yield)
:
	/Users/thomas.franklin/ace/ace/lib/ace/fork_util.rb:33:in `isolate'
	/Users/thomas.franklin/ace/ace/lib/ace/plugin_cache.rb:23:in `with_synced_libdir'
	/Users/thomas.franklin/ace/ace/lib/ace/transport_app.rb:114:in `block in <class:TransportApp>'
```

**Comment by DavidS** [comment]
Good catch - why did the unit tests not see that?

**Comment by Thomas-Franklin** [comment]
> Good catch - why did the unit tests not see that?

Probably my doing - can review them tomorrow with you and maybe I've missed a test that could/should be there

**Comment by Thomas-Franklin** [comment]
@DavidS  I've fixed up the expectations on the plugincache specs to behave as expected - verified by removing the `&block` additions in plugin_cache and the new tests fail.

**Pull request merged**
