### PR TITLE
(FM-7952) allow reports from ACE in testing auth.conf

### PR DESCRIPTION
**Pull request by DavidS**
Also adds some notes for linux users when using the compose for testing.

### CODE REVIEW

**Comment by DavidS** [comment]
cc @Thomas-Franklin this change allowed me to run your in-flight test against the composed puppetserver

**Comment by Thomas-Franklin** [comment]
@DavidS looks good to me, this will still need to be the certname for puppetenterprisemodules? As we just reuse the orchestrator master certname I believe

**Comment by DavidS** [comment]
https://github.com/puppetlabs/puppet-enterprise-modules/pull/222

**Comment by Thomas-Franklin** [comment]
> [puppetlabs/puppet-enterprise-modules#222](https://github.com/puppetlabs/puppet-enterprise-modules/pull/222)

Was just making sure I understood correctly :-D 👍

**Pull request merged**
